tardis/urls.py
from django.contrib import admin
admin.autodiscover()
from django.contrib.auth.views import logout
from django.conf.urls.defaults import patterns, include
from django.views.generic import list_detail
from django.conf import settings
from registration.views import register

from tardis.tardis_portal.models import Equipment
from tardis.tardis_portal.views import getNewSearchDatafileSelectionForm
from tardis.tardis_portal.forms import RegistrationForm

core_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^$', 'index'),
    (r'^site-settings.xml/$', 'site_settings'),
    (r'^about/$', 'about'),
    (r'^partners/$', 'partners'),
    (r'^stats/$', 'stats'),
    (r'^import_params/$', 'import_params'),
)

experiment_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^view/(?P<experiment_id>\d+)/$', 'view_experiment'),
    (r'^edit/(?P<experiment_id>\d+)/$', 'edit_experiment'),
    (r'^view/$', 'experiment_index'),
    (r'^register/$', 'register_experiment_ws_xmldata'),
    (r'^register/internal/$', 'register_experiment_ws_xmldata_internal'),
    (r'^view/(?P<experiment_id>\d+)/publish/$', 'publish_experiment'),
    (r'^create/$', 'create_experiment'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/add/user/'
     '(?P<username>[\w\.]+)$', 'add_experiment_access_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/remove/user/'
     '(?P<username>[\w\.]+)/$', 'remove_experiment_access_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/change/user/'
     '(?P<username>[\w\.]+)/$', 'change_user_permissions'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/user/$',
     'retrieve_access_list_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/add/group/'
     '(?P<groupname>[\w\s\.]+)$', 'add_experiment_access_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/remove/group/'
     '(?P<group_id>\d+)/$', 'remove_experiment_access_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/change/group/'
     '(?P<group_id>\d+)/$', 'change_group_permissions'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/group/$',
     'retrieve_access_list_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/external/$',
     'retrieve_access_list_external'),
    (r'^control_panel/$', 'control_panel'),

    )

accounts_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^login/$', 'login'),
    (r'^manage_auth_methods/$', 'manage_auth_methods'),
    (r'^register/$', register,
     {'form_class': RegistrationForm}),
    (r'', include('registration.urls')),
    )

ajax_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^parameters/(?P<dataset_file_id>\d+)/$', 'retrieve_parameters'),
    (r'^xml_data/(?P<dataset_file_id>\d+)/$', 'retrieve_xml_data'),
    (r'^datafile_list/(?P<dataset_id>\d+)/$', 'retrieve_datafile_list'),
    (r'^user_list/$', 'retrieve_user_list'),
    (r'^group_list/$', 'retrieve_group_list'),
    (r'^upload_complete/$', 'upload_complete'),
    (r'^upload_files/(?P<dataset_id>\d+)/$', 'upload_files'),
    (r'^experiment_description/(?P<experiment_id>\d+)/$',
     'experiment_description'),
    (r'^experiment_datasets/(?P<experiment_id>\d+)/$', 'experiment_datasets'),
    )

download_urls = patterns(
    'tardis.tardis_portal.download',
    (r'^datafile/(?P<datafile_id>\d+)/$', 'download_datafile'),
    #(r'^dataset/(?P<dataset_id>\d+)/$', 'download_dataset'),
    (r'^experiment/(?P<experiment_id>\d+)/$', 'download_experiment'),
    (r'^datafiles/$', 'download_datafiles'),
    )

search_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^equipment/$', 'search_equipment'),
    (r'^experiment/$', 'search_experiment'),
    (r'^datafile/$', 'search_datafile'),
    )

group_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^(?P<group_id>\d+)/$', 'retrieve_group_userlist'),
    (r'^(?P<group_id>\d+)/add/(?P<username>[\w\.]+)$',
     'add_user_to_group'),
    (r'^(?P<group_id>\d+)/remove/(?P<username>[\w\.]+)/$',
     'remove_user_from_group'),
    )

apppatterns = patterns('',)
for app in settings.TARDIS_APPS:
    apppatterns += patterns('tardis.apps',
                            (r'^%s/' % app,
                             include('%s.%s.urls' %
                                     (settings.TARDIS_APP_ROOT, app))))

urlpatterns = patterns(
    # (r'^search/quick/$', 'tardis.tardis_portal.views.search_quick'),
    '',
    (r'', include(core_urls)),

    # Experiment Views
    (r'^experiment/', include(experiment_urls)),

    # Download Views
    (r'^download/', include(download_urls)),

    # Ajax Views
    (r'^ajax/', include(ajax_urls)),

    # Seach Views
    (r'^search/', include(search_urls)),

    # Account Views
    (r'^accounts/', include(accounts_urls)),

    # Group Views
    (r'^groups/$', 'tardis.tardis_portal.views.manage_groups'),
    (r'^group/', include(group_urls)),

    # Equipment Views
    (r'^equipment/$', list_detail.object_list,
     {'queryset': Equipment.objects.all(),
      'paginate_by': 15,
      'extra_context':
      {'searchDatafileSelectionForm': getNewSearchDatafileSelectionForm()}}),
    (r'^equipment/(?P<object_id>\d+)/$', list_detail.object_detail,
     {'queryset': Equipment.objects.all()}),

    # Display Views
    (r'^displayExperimentImage/(?P<experiment_id>\d+)/'
     '(?P<parameterset_id>\d+)/(?P<parameter_name>\w+)/$',
     'tardis.tardis_portal.views.display_experiment_image'),
    (r'^displayDatasetImage/(?P<dataset_id>\d+)/(?P<parameterset_id>\d+)/'
     '(?P<parameter_name>\w+)/$',
     'tardis.tardis_portal.views.display_dataset_image'),
    (r'^displayDatafileImage/(?P<dataset_file_id>\d+)/'
     '(?P<parameterset_id>\d+)/(?P<parameter_name>\w+)/$',
    'tardis.tardis_portal.views.display_datafile_image'),

    # Login/out
    (r'^login/$', 'tardis.tardis_portal.views.login'),
    (r'^logout/$', logout, {'next_page': '/'}),

    # Media
    (r'site_media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.STATIC_DOC_ROOT}),
    (r'media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.ADMIN_MEDIA_STATIC_DOC_ROOT}),

    # Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^upload/(?P<dataset_id>\d+)/$', 'tardis.tardis_portal.views.upload'),

    # Apps
    (r'^apps/', include(apppatterns)),
)

tardis/tardis_portal/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010-2011, Monash e-Research Centre
#   (Monash University, Australia)
# Copyright (c) 2010-2011, VeRSI Consortium
#   (Victorian eResearch Strategic Initiative, Australia)
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    *  Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    *  Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#    *  Neither the name of the VeRSI, the VeRSI Consortium members, nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

"""
models.py

.. moduleauthor:: Steve Androulakis <steve.androulakis@monash.edu>
.. moduleauthor:: Gerson Galang <gerson.galang@versi.edu.au>
.. moduleauthor:: Russell Sim <russell.sim@monash.edu>

"""

from os import path
from urlparse import urlparse

from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import User, Group
from django.utils.safestring import SafeUnicode

from tardis.tardis_portal.managers import ExperimentManager
from tardis.tardis_portal.managers import DatasetParameterManager


class UserProfile(models.Model):
    """
    UserProfile class is an extension to the Django standard user model.

    :attribute isDjangoAccount: is the user a local DB user
    :attribute user: a foreign key to the
       :class:`django.contrib.auth.models.User`
    """
    user = models.ForeignKey(User, unique=True)

    # This flag will tell us if the main User account was created using any
    # non localdb auth methods. For example, if a first time user authenticates
    # to the system using the VBL auth method, an account will be created for
    # him, say "vbl_user001" and the field isDjangoAccount will be set to
    # False.
    isDjangoAccount = models.BooleanField(
        null=False, blank=False, default=True)

    def getUserAuthentications(self):
        return self.userAuthentication_set.all()

    def __unicode__(self):
        return self.user.username


class GroupAdmin(models.Model):
    """GroupAdmin links the Django User and Group tables for group
    administrators

    :attribute user: a forign key to the
       :class:`django.contrib.auth.models.User`
    :attribute group: a forign key to the
       :class:`django.contrib.auth.models.Group`
    """

    user = models.ForeignKey(User)
    group = models.ForeignKey(Group)

    def __unicode__(self):
        return '%s: %s' % (self.user.username, self.group.name)


# TODO: Generalise auth methods
class UserAuthentication(models.Model):
    CHOICES = ()
    userProfile = models.ForeignKey(UserProfile)
    username = models.CharField(max_length=50)
    authenticationMethod = models.CharField(max_length=30, choices=CHOICES)

    def __init__(self, *args, **kwargs):
        # instantiate comparisonChoices based on settings.AUTH PROVIDERS
        self.CHOICES = ()
        for authMethods in settings.AUTH_PROVIDERS:
            self.CHOICES += ((authMethods[0], authMethods[1]),)
        self._comparisonChoicesDict = dict(self.CHOICES)

        super(UserAuthentication, self).__init__(*args, **kwargs)

    def getAuthMethodDescription(self):
        return self._comparisonChoicesDict[self.authenticationMethod]

    def __unicode__(self):
        return self.username + ' - ' + self.getAuthMethodDescription()


class XSLT_docs(models.Model):

    xmlns = models.URLField(max_length=255, primary_key=True)
    data = models.TextField()

    def __unicode__(self):
        return self.xmlns


class Experiment(models.Model):
    """The ``Experiment`` model inherits from :class:`django.db.models.Model`

    :attribute url: **Undocumented**
    :attribute approved: **Undocumented**
    :attribute title: the title of the experiment.
    :attribute institution_name: the name of the institution who created
       the dataset.
    :attribute start_time: **Undocumented**
    :attribute end_time: **Undocumented**
    :attribute created_time: **Undocumented**
    :attribute handle: **Undocumented**
    :attribute public: **Undocumented**
    :attribute objects: default model manager
    :attribute safe: ACL aware model manager

    """
    url = models.URLField(verify_exists=False, max_length=255,
                          null=True, blank=True)
    approved = models.BooleanField()
    title = models.CharField(max_length=400)
    institution_name = models.CharField(max_length=400)
    description = models.TextField(blank=True)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User)
    handle = models.TextField(null=True, blank=True)
    public = models.BooleanField()
    objects = models.Manager()  # The default manager.
    safe = ExperimentManager()  # The acl-aware specific manager.

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        """Return the absolute url to the current ``Experiment``"""
        return ('tardis.tardis_portal.views.view_experiment', (),
                {'experiment_id': self.id})

    @models.permalink
    def get_edit_url(self):
        """Return the absolute url to the edit view of the current
        ``Experiment``

        """
        return ('tardis.tardis_portal.views.edit_experiment', (),
                {'experiment_id': self.id})


class ExperimentACL(models.Model):
    """The ExperimentACL table is the core of the `Tardis Authorisation framework
    <http://code.google.com/p/mytardis/wiki/AuthorisationEngineAlt>`_

    :attribute pluginId: the the name of the auth plugin being used
    :attribute entityId: a foreign key to auth plugins
    :attribute experimentId: a forign key to the
       :class:`tardis.tardis_portal.models.Experiment`
    :attribute canRead: gives the user read access
    :attribute canWrite: gives the user write access
    :attribute canDelete: gives the user delete permission
    :attribute isOwner: the experiment owner flag.
    :attribute effectiveDate: the date when access takes into effect
    :attribute expiryDate: the date when access ceases
    :attribute aclOwnershipType: system-owned or user-owned.

    System-owned ACLs will prevent users from removing or
    editing ACL entries to a particular experiment they
    own. User-owned ACLs will allow experiment owners to
    remove/add/edit ACL entries to the experiments they own.

    """

    OWNER_OWNED = 1
    SYSTEM_OWNED = 2
    __COMPARISON_CHOICES = (
        (OWNER_OWNED, 'Owner-owned'),
        (SYSTEM_OWNED, 'System-owned'),
    )

    pluginId = models.CharField(null=False, blank=False, max_length=30)
    entityId = models.CharField(null=False, blank=False, max_length=320)
    experiment = models.ForeignKey(Experiment)
    canRead = models.BooleanField(default=False)
    canWrite = models.BooleanField(default=False)
    canDelete = models.BooleanField(default=False)
    isOwner = models.BooleanField(default=False)
    effectiveDate = models.DateField(null=True, blank=True)
    expiryDate = models.DateField(null=True, blank=True)
    aclOwnershipType = models.IntegerField(
        choices=__COMPARISON_CHOICES, default=OWNER_OWNED)

    def __unicode__(self):
        return '%i | %s' % (self.experiment.id, self.experiment.title)

    class Meta:
        ordering = ['experiment__id']


class Author_Experiment(models.Model):

    experiment = models.ForeignKey(Experiment)
    author = models.CharField(max_length=255)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ('order', )

    def __unicode__(self):
        return SafeUnicode(self.author.name) + ' | ' \
            + SafeUnicode(self.experiment.id) + ' | ' \
            + SafeUnicode(self.order)

    class Meta:
        ordering = ['order']
        unique_together = (('experiment', 'author'),)


class Dataset(models.Model):
    """Class to link datasets to experiments

    :attribute experiment: a forign key to the
       :class:`tardis.tardis_portal.models.Experiment`
    :attribute description: description of this dataset
    """

    experiment = models.ForeignKey(Experiment)
    description = models.TextField(blank=True)

    def addDatafile(self, filepath,
                    protocol='', url='',
                    size=None, commit=True):
        """Add Datafile helper function

        :param filepath: the file path within the repository
        :type filepath: string
        """
        full_file_path = path.join(settings.FILE_STORE_PATH,
                                   str(self.experiment.id),
                                   filepath)

tardis/tardis_portal/templates/tardis_portal/auth_methods.html
<!--
 Copyright (c) 2010, Monash e-Research Centre
   (Monash University, Australia)
 Copyright (c) 2010, VeRSI Consortium
   (Victorian eResearch Strategic Initiative, Australia)
 All rights reserved.
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
    *  Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
    *  Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
    *  Neither the name of the VeRSI, the VeRSI Consortium members, nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
 EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
{% extends "tardis_portal/data_browsing_template.html" %}
{% block content %}
<div id="content">
    <div id="authList">
	<p/>
	{% for userAuth in userAuthMethodList %}
	    <div class="authMethod" id="{{ userAuth.2 }}">
	    <table>
	    <tr>
		<td><strong>username:</strong></td><td> {{ userAuth.0 }} &nbsp;
		{% if userAuth.1 == 'Local DB' %}
		<a class="edit_auth" id="{{ userAuth.2 }}" href="javascript:void(0);"><img src="/site_media/images/icon_changelink.gif"></a>
        {% else %}
	        {% if isADjangoAccount %}
	        <a class="remove_auth" id="{{ userAuth.2 }}" href="javascript:void(0);"><img src="/site_media/images/icon_deletelink.gif"></a>
	        {% endif %}
        {% endif %}
		</td>
        </tr>
		<tr>
        <td><strong>auth method:</strong></td><td>{{ userAuth.1 }}</td>
        </tr>
        <tr><td rowspan="2">&nbsp;</td></tr>
        </table>
		</div> <!-- authMethod -->
	{% endfor %}
	</div> <!--  authList -->
	<p/>
	<div id="authForm">
	{% if supportedAuthMethods|length > 0 %}
		Add a new account:
		<form action="." method="POST"">
		<table>
          {% for field in authForm %}
          <tr>
            <td style="text-align:right">{{ field.label_tag }}:</td><td>{{ field }}</td> 
          </tr>
          {% endfor %}
          <tr>
            <td>&nbsp;</td><td><input type="submit" value="Link the Accounts" id="link"></td>
          </tr>
        </table>
		</form>
		
	{% endif %}
	</div>
</div>

<script>
var showChangePasswordForm = 0;
var authMethodDict = [];
{% for authKey, authDesc in allAuthMethods.items %}
authMethodDict["{{ authKey }}"] = "{{ authDesc }}";
{% endfor %}

var remove_auth = function(event) {
    if (confirm("Are you sure you want to delete this authentication method?")) {
        var divId = this.id;
        var data = { operation: 'removeAuth', authMethod: divId };
		$.post("/accounts/manage_auth_methods/", data, function(data) {
	        var status = data.status;
	        if (status == "success") {
	        	$('div').remove('#' + divId + '.authMethod');
	            $('<option value="' + divId + '">' + authMethodDict[divId] + '</option>').insertAfter($("option:last"));
	        }
	        else {
	            display_error(data.errorMessage, $("div #" + divId + ".authMethod"));
	        }   
	    }, "json");
    }
}

var edit_auth = function(event) {
	var divId = this.id;
	if (showChangePasswordForm == 0) {
		var changePasswordFormStr = 
		'<div class="changePassword">' +
		'<form action="." method="POST">' +
	    '<table>' +
	    '<tr><td><label for="id_currentPassword">Current Password:</label></td><td><input id="id_currentPassword" type="password" name="currentPassword" /></td></tr>' + 
		'<tr><td><label for="id_password">New Password:</label></td><td><input id="id_password" type="password" name="password" /></td></tr>' + 
		'<tr><td><label for="id_password1">Confirm Password:</label></td><td><input id="id_password1" type="password" name="password1" /></td></tr>' + 
	    '<tr><td>&nbsp;</td><td><input type="submit" value="Change Password" id="edit"></td></tr>' + 
	    '</table>' +
	    '</form>' +
	    '</div>';
	    var changePassword = $(changePasswordFormStr);
	    showChangePasswordForm = 1;
	    changePassword.insertAfter('#' + divId + '.authMethod');
	    var replacementImg = '<img src="/site_media/images/minus-8.png">';
	    $('#' + divId + '.edit_auth img').replaceWith(replacementImg);
	}
	else {
		showChangePasswordForm = 0;
		$('div').remove('.changePassword');
		var replacementImg = '<img src="/site_media/images/icon_changelink.gif">';
        $('#' + divId + '.edit_auth img').replaceWith(replacementImg);
	}
}

var process_new_auth_entry = function(data) {
	var dataMap = data.data;
	var username = dataMap.username;
	var authenticationMethod = dataMap.authenticationMethod;

	var auth_method_str = '<div class="authMethod" id="' + authenticationMethod + '">\n';
	auth_method_str += '<table><tr><td><strong>username:</strong></td><td>' + username;
	auth_method_str += '&nbsp;<a class="remove_auth" id="' + authenticationMethod + '" href="javascript:void(0);"><img src="/site_media/images/icon_deletelink.gif"></a></td></tr>\n';
	auth_method_str += '<tr><td><strong>auth method:</strong></td><td>' + authMethodDict[authenticationMethod] + '</td></tr>\n';
	auth_method_str += '<tr><td rowspan="2">&nbsp;</td></tr></table>';
    auth_method_str += '</div>\n'
	var new_auth_method = $(auth_method_str);
	new_auth_method.insertAfter($(".authMethod:last"));

    var supportedAuthMethodsLength = dataMap.supportedAuthMethodsLen;
    if (supportedAuthMethodsLength == 0) {
    	$('div').remove('#authForm');
    }
    else {
        $('option').remove("option[value='" + authenticationMethod + "']");
        $("#id_username").val("");
        $("#id_password").val("");
    }
	
};

var edit_account = function() {
	var currentPassword = $("#id_currentPassword").val();
    var password = $("#id_password").val();
    var password1 = $("#id_password1").val();

    if (currentPassword == "" || password == "" || password1 == "") {
    	display_error("Sorry, all the password fields should be filled.", $("div .changePassword"));
    }
    else if (password != password1) {
        display_error("The passwords don't match.", $("div .changePassword"));
    }
    else {
    	var data = { operation: 'editAuth', currentPassword: currentPassword, newPassword: password };
        $.post("/accounts/manage_auth_methods/", data, function(data) {
            var status = data.status;
            if (status == "success") {
                showChangePasswordForm = 0;
                $('div').remove('.changePassword');
                var replacementImg = '<img src="/site_media/images/icon_changelink.gif">';
                $('a img').replaceWith(replacementImg);
                var msg_div = $('<div"><b>Password successfully changed</b></div>');
                msg_div.insertAfter('.authMethod').fadeIn("slow").animate({opacity: 1.0}, 5000).fadeOut("slow",function() { msg_div.remove(); });
            }
            else {
                display_error(data.errorMessage, $("div .changePassword"));
            }   
        }, "json");
    }
    return false;
};

var link_account = function() {
	var username = $("#id_username").val();
    var password = $("#id_password").val();
    var authenticationMethod = $("#id_authenticationMethod").val();

    if (username != "" && password != "" && authenticationMethod != "") {
        var data = { operation: 'addAuth', username: username, password: password, authenticationMethod: authenticationMethod };
        $.post("/accounts/manage_auth_methods/", data, function(data) {
            var status = data.status;
            if (status == "success") {
            	process_new_auth_entry(data);
            }
            else if (status == "confirm") {
            	var confirmMessage = "This process would involve merging the two accounts you own.\nWould you like to continue?"
                if (confirm(confirmMessage)) {
                	data = { operation: 'mergeAuth', username: username, password: password, authenticationMethod: authenticationMethod };
                	$.post("/accounts/manage_auth_methods/", data, function(data) {
                    	var status = data.status
                		if (status == "success") {
                			process_new_auth_entry(data);
                        }
                        else {
                        	alert("done merging failed");
                        }
                	}, "json");
                }
            }
            else {
            	display_error(data.errorMessage, $("#authForm"));
            }   
        }, "json");
    }
    else {
        display_error("You need to provide all the necessary information to authenticate.", $("#authForm"));
    }
	return false;
};

var display_error = function(msg, elem) {
	  var msg_div = $('<div id="statusBoxError">'+msg+'</div>');
	  msg_div.insertBefore(elem).fadeIn("slow").animate({opacity: 1.0}, 5000).fadeOut("slow",function() { msg_div.remove(); });
};

$("#link").click(link_account);
$("#edit").live('click', edit_account);
$(".edit_auth").live('click', edit_auth);
$(".remove_auth").live('click', remove_auth);

</script>
{% endblock %}
</p><p/>

tardis/tardis_portal/templates/tardis_portal/equipment_detail.html
{% extends "tardis_portal/portal_template.html" %}

{% block content %}
<div id="content">
  <div class="post">
    <h1 class="title"><a href="#">{{ object.key }}</a></h1>
    <div class="entry">
      <table>
	{% if object.type %}
	<tr>
	  <td>Type:</td>
	  <td>{{ object.type }}</td>
	</tr>
	{% endif %}
	{% if object.make %}
	<tr>
	  <td>Make:</td>
	  <td>{{ object.make }}</td>
	</tr>
	{% endif %}
	{% if object.model %}
	<tr>
	  <td>Model:</td>
	  <td>{{ object.model }}</td>
	</tr>
	{% endif %}
	{% if object.serial %}
	<tr>
	  <td>Serial:</td>
	  <td>{{ object.serial }}</td>
	</tr>
	{% endif %}
	{% if object.description %}
	<tr>
	  <td valign="top">Description:</td>
	  <td>{{ object.description|linebreaks }}</td>
	</tr>
	{% endif %}
	{% if object.comm %}
	<tr>
	  <td>Commissioned:</td>
	  <td>{{ object.comm }}</td>
	</tr>
	{% endif %}
	{% if object.decom %}
	<tr>
	  <td>Decommissioned:</td>
	  <td>{{ object.decomm }}</td>
	</tr>
	{% endif %}
      </table>
      <a href="{{ object.url }}">{{ object.url }}</a>
    </div> <!-- entry -->
  </div> <!-- post -->
</div> <!-- content -->
{% endblock %}

tardis/tardis_portal/templates/tardis_portal/upload_complete.html
<p>Number: {{ numberOfFiles }}</p>
<p>Errors: {{ errorCount }}</p>
<p>Bytes: {{ bytes }}</p>
<p>Speed: {{ speed }}</p>