tardis/urls.py
from django.contrib import admin
admin.autodiscover()
from django.contrib.auth.views import logout
from django.conf.urls.defaults import patterns, include
from django.views.generic import list_detail
from django.conf import settings
from registration.views import register

from tardis.tardis_portal.models import Equipment
from tardis.tardis_portal.views import getNewSearchDatafileSelectionForm
from tardis.tardis_portal.forms import RegistrationForm

core_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^$', 'index'),
    (r'^site-settings.xml/$', 'site_settings'),
    (r'^about/$', 'about'),
    (r'^partners/$', 'partners'),
    (r'^stats/$', 'stats'),
    (r'^import_params/$', 'import_params'),
)

experiment_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^view/(?P<experiment_id>\d+)/$', 'view_experiment'),
    (r'^edit/(?P<experiment_id>\d+)/$', 'edit_experiment'),
    (r'^view/$', 'experiment_index'),
    (r'^register/$', 'register_experiment_ws_xmldata'),
    (r'^register/internal/$', 'register_experiment_ws_xmldata_internal'),
    (r'^view/(?P<experiment_id>\d+)/publish/$', 'publish_experiment'),
    (r'^create/$', 'create_experiment'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/add/user/'
     '(?P<username>[\w\.]+)$', 'add_experiment_access_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/remove/user/'
     '(?P<username>[\w\.]+)/$', 'remove_experiment_access_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/change/user/'
     '(?P<username>[\w\.]+)/$', 'change_user_permissions'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/user/$',
     'retrieve_access_list_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/add/group/'
     '(?P<groupname>[\w\s\.]+)$', 'add_experiment_access_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/remove/group/'
     '(?P<group_id>\d+)/$', 'remove_experiment_access_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/change/group/'
     '(?P<group_id>\d+)/$', 'change_group_permissions'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/group/$',
     'retrieve_access_list_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/external/$',
     'retrieve_access_list_external'),
    (r'^control_panel/$', 'control_panel'),

    )

accounts_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^login/$', 'login'),
    (r'^manage_auth_methods/$', 'manage_auth_methods'),
    (r'^register/$', register,
     {'form_class': RegistrationForm}),
    (r'', include('registration.urls')),
    )

ajax_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^parameters/(?P<dataset_file_id>\d+)/$', 'retrieve_parameters'),
    (r'^xml_data/(?P<dataset_file_id>\d+)/$', 'retrieve_xml_data'),
    (r'^datafile_list/(?P<dataset_id>\d+)/$', 'retrieve_datafile_list'),
    (r'^user_list/$', 'retrieve_user_list'),
    (r'^group_list/$', 'retrieve_group_list'),
    (r'^upload_complete/$', 'upload_complete'),
    (r'^upload_files/(?P<dataset_id>\d+)/$', 'upload_files'),
    (r'^experiment_description/(?P<experiment_id>\d+)/$',
     'experiment_description'),
    (r'^experiment_datasets/(?P<experiment_id>\d+)/$', 'experiment_datasets'),
    )

download_urls = patterns(
    'tardis.tardis_portal.download',
    (r'^datafile/(?P<datafile_id>\d+)/$', 'download_datafile'),
    #(r'^dataset/(?P<dataset_id>\d+)/$', 'download_dataset'),
    (r'^experiment/(?P<experiment_id>\d+)/$', 'download_experiment'),
    (r'^datafiles/$', 'download_datafiles'),
    )

search_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^equipment/$', 'search_equipment'),
    (r'^experiment/$', 'search_experiment'),
    (r'^datafile/$', 'search_datafile'),
    )

group_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^(?P<group_id>\d+)/$', 'retrieve_group_userlist'),
    (r'^(?P<group_id>\d+)/add/(?P<username>[\w\.]+)$',
     'add_user_to_group'),
    (r'^(?P<group_id>\d+)/remove/(?P<username>[\w\.]+)/$',
     'remove_user_from_group'),
    )

apppatterns = patterns('',)
for app in settings.TARDIS_APPS:
    apppatterns += patterns('tardis.apps',
                            (r'^%s/' % app,
                             include('%s.%s.urls' %
                                     (settings.TARDIS_APP_ROOT, app))))

urlpatterns = patterns(
    # (r'^search/quick/$', 'tardis.tardis_portal.views.search_quick'),
    '',
    (r'', include(core_urls)),

    # Experiment Views
    (r'^experiment/', include(experiment_urls)),

    # Download Views
    (r'^download/', include(download_urls)),

    # Ajax Views
    (r'^ajax/', include(ajax_urls)),

    # Seach Views
    (r'^search/', include(search_urls)),

    # Account Views
    (r'^accounts/', include(accounts_urls)),

    # Group Views
    (r'^groups/$', 'tardis.tardis_portal.views.manage_groups'),
    (r'^group/', include(group_urls)),

    # Equipment Views
    (r'^equipment/$', list_detail.object_list,
     {'queryset': Equipment.objects.all(),
      'paginate_by': 15,
      'extra_context':
      {'searchDatafileSelectionForm': getNewSearchDatafileSelectionForm()}}),
    (r'^equipment/(?P<object_id>\d+)/$', list_detail.object_detail,
     {'queryset': Equipment.objects.all()}),

    # Display Views
    (r'^displayExperimentImage/(?P<experiment_id>\d+)/'
     '(?P<parameterset_id>\d+)/(?P<parameter_name>\w+)/$',
     'tardis.tardis_portal.views.display_experiment_image'),
    (r'^displayDatasetImage/(?P<dataset_id>\d+)/(?P<parameterset_id>\d+)/'
     '(?P<parameter_name>\w+)/$',
     'tardis.tardis_portal.views.display_dataset_image'),
    (r'^displayDatafileImage/(?P<dataset_file_id>\d+)/'
     '(?P<parameterset_id>\d+)/(?P<parameter_name>\w+)/$',
    'tardis.tardis_portal.views.display_datafile_image'),

    # Login/out
    (r'^login/$', 'tardis.tardis_portal.views.login'),
    (r'^logout/$', logout, {'next_page': '/'}),

    # Media
    (r'site_media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.STATIC_DOC_ROOT}),
    (r'media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.ADMIN_MEDIA_STATIC_DOC_ROOT}),

    # Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^upload/(?P<dataset_id>\d+)/$', 'tardis.tardis_portal.views.upload'),

    # Apps
    (r'^apps/', include(apppatterns)),
)

tardis/tardis_portal/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010-2011, Monash e-Research Centre
#   (Monash University, Australia)
# Copyright (c) 2010-2011, VeRSI Consortium
#   (Victorian eResearch Strategic Initiative, Australia)
# All rights reserved.
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    *  Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#    *  Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#    *  Neither the name of the VeRSI, the VeRSI Consortium members, nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

"""
models.py

.. moduleauthor:: Steve Androulakis <steve.androulakis@monash.edu>
.. moduleauthor:: Gerson Galang <gerson.galang@versi.edu.au>
.. moduleauthor:: Russell Sim <russell.sim@monash.edu>

"""

from os import path
from urlparse import urlparse

from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.contrib.auth.models import User, Group
from django.utils.safestring import SafeUnicode

from tardis.tardis_portal.managers import ExperimentManager
from tardis.tardis_portal.managers import DatasetParameterManager


class UserProfile(models.Model):
    """
    UserProfile class is an extension to the Django standard user model.

    :attribute isDjangoAccount: is the user a local DB user
    :attribute user: a foreign key to the
       :class:`django.contrib.auth.models.User`
    """
    user = models.ForeignKey(User, unique=True)

    # This flag will tell us if the main User account was created using any
    # non localdb auth methods. For example, if a first time user authenticates
    # to the system using the VBL auth method, an account will be created for
    # him, say "vbl_user001" and the field isDjangoAccount will be set to
    # False.
    isDjangoAccount = models.BooleanField(
        null=False, blank=False, default=True)

    def getUserAuthentications(self):
        return self.userAuthentication_set.all()

    def __unicode__(self):
        return self.user.username


class GroupAdmin(models.Model):
    """GroupAdmin links the Django User and Group tables for group
    administrators

    :attribute user: a forign key to the
       :class:`django.contrib.auth.models.User`
    :attribute group: a forign key to the
       :class:`django.contrib.auth.models.Group`
    """

    user = models.ForeignKey(User)
    group = models.ForeignKey(Group)

    def __unicode__(self):
        return '%s: %s' % (self.user.username, self.group.name)


# TODO: Generalise auth methods
class UserAuthentication(models.Model):
    CHOICES = ()
    userProfile = models.ForeignKey(UserProfile)
    username = models.CharField(max_length=50)
    authenticationMethod = models.CharField(max_length=30, choices=CHOICES)

    def __init__(self, *args, **kwargs):
        # instantiate comparisonChoices based on settings.AUTH PROVIDERS
        self.CHOICES = ()
        for authMethods in settings.AUTH_PROVIDERS:
            self.CHOICES += ((authMethods[0], authMethods[1]),)
        self._comparisonChoicesDict = dict(self.CHOICES)

        super(UserAuthentication, self).__init__(*args, **kwargs)

    def getAuthMethodDescription(self):
        return self._comparisonChoicesDict[self.authenticationMethod]

    def __unicode__(self):
        return self.username + ' - ' + self.getAuthMethodDescription()


class XSLT_docs(models.Model):

    xmlns = models.URLField(max_length=255, primary_key=True)
    data = models.TextField()

    def __unicode__(self):
        return self.xmlns


class Experiment(models.Model):
    """The ``Experiment`` model inherits from :class:`django.db.models.Model`

    :attribute url: **Undocumented**
    :attribute approved: **Undocumented**
    :attribute title: the title of the experiment.
    :attribute institution_name: the name of the institution who created
       the dataset.
    :attribute start_time: **Undocumented**
    :attribute end_time: **Undocumented**
    :attribute created_time: **Undocumented**
    :attribute handle: **Undocumented**
    :attribute public: **Undocumented**
    :attribute objects: default model manager
    :attribute safe: ACL aware model manager

    """
    url = models.URLField(verify_exists=False, max_length=255,
                          null=True, blank=True)
    approved = models.BooleanField()
    title = models.CharField(max_length=400)
    institution_name = models.CharField(max_length=400)
    description = models.TextField(blank=True)
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User)
    handle = models.TextField(null=True, blank=True)
    public = models.BooleanField()
    objects = models.Manager()  # The default manager.
    safe = ExperimentManager()  # The acl-aware specific manager.

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        """Return the absolute url to the current ``Experiment``"""
        return ('tardis.tardis_portal.views.view_experiment', (),
                {'experiment_id': self.id})

    @models.permalink
    def get_edit_url(self):
        """Return the absolute url to the edit view of the current
        ``Experiment``

        """
        return ('tardis.tardis_portal.views.edit_experiment', (),
                {'experiment_id': self.id})


class ExperimentACL(models.Model):
    """The ExperimentACL table is the core of the `Tardis Authorisation framework
    <http://code.google.com/p/mytardis/wiki/AuthorisationEngineAlt>`_

    :attribute pluginId: the the name of the auth plugin being used
    :attribute entityId: a foreign key to auth plugins
    :attribute experimentId: a forign key to the
       :class:`tardis.tardis_portal.models.Experiment`
    :attribute canRead: gives the user read access
    :attribute canWrite: gives the user write access
    :attribute canDelete: gives the user delete permission
    :attribute isOwner: the experiment owner flag.
    :attribute effectiveDate: the date when access takes into effect
    :attribute expiryDate: the date when access ceases
    :attribute aclOwnershipType: system-owned or user-owned.

    System-owned ACLs will prevent users from removing or
    editing ACL entries to a particular experiment they
    own. User-owned ACLs will allow experiment owners to
    remove/add/edit ACL entries to the experiments they own.

    """

    OWNER_OWNED = 1
    SYSTEM_OWNED = 2
    __COMPARISON_CHOICES = (
        (OWNER_OWNED, 'Owner-owned'),
        (SYSTEM_OWNED, 'System-owned'),
    )

    pluginId = models.CharField(null=False, blank=False, max_length=30)
    entityId = models.CharField(null=False, blank=False, max_length=320)
    experiment = models.ForeignKey(Experiment)
    canRead = models.BooleanField(default=False)
    canWrite = models.BooleanField(default=False)
    canDelete = models.BooleanField(default=False)
    isOwner = models.BooleanField(default=False)
    effectiveDate = models.DateField(null=True, blank=True)
    expiryDate = models.DateField(null=True, blank=True)
    aclOwnershipType = models.IntegerField(
        choices=__COMPARISON_CHOICES, default=OWNER_OWNED)

    def __unicode__(self):
        return '%i | %s' % (self.experiment.id, self.experiment.title)

    class Meta:
        ordering = ['experiment__id']


class Author_Experiment(models.Model):

    experiment = models.ForeignKey(Experiment)
    author = models.CharField(max_length=255)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ('order', )

    def __unicode__(self):
        return SafeUnicode(self.author.name) + ' | ' \
            + SafeUnicode(self.experiment.id) + ' | ' \
            + SafeUnicode(self.order)

    class Meta:
        ordering = ['order']
        unique_together = (('experiment', 'author'),)


class Dataset(models.Model):
    """Class to link datasets to experiments

    :attribute experiment: a forign key to the
       :class:`tardis.tardis_portal.models.Experiment`
    :attribute description: description of this dataset
    """

    experiment = models.ForeignKey(Experiment)
    description = models.TextField(blank=True)

    def addDatafile(self, filepath,
                    protocol='', url='',
                    size=None, commit=True):
        """Add Datafile helper function

        :param filepath: the file path within the repository
        :type filepath: string
        """
        full_file_path = path.join(settings.FILE_STORE_PATH,
                                   str(self.experiment.id),
                                   filepath)

tardis/tardis_portal/templates/tardis_portal/ajax/access_list_user.html
<!--
 Copyright (c) 2010, Monash e-Research Centre
   (Monash University, Australia)
 Copyright (c) 2010, VeRSI Consortium
   (Victorian eResearch Strategic Initiative, Australia)
 All rights reserved.
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

    *  Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
    *  Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
    *  Neither the name of the VeRSI, the VeRSI Consortium members, nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY
 EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->
<div class="users">
{% for user in users %}
  {% include "tardis_portal/ajax/add_user_result.html" %}
{% endfor %}
</div> <!-- users -->
<p>
  <label>Add user: </label>
  <input type="text" class="usersuggest" name="adduser" />
  <a class="form_submit" id="user" href="">Submit</a><br/>
  <input type="checkbox" name="read" class="canRead"  checked="yes" /> READ <br/>
  <input type="checkbox" name="write" class="canWrite" /> WRITE <br/>
  <input type="checkbox" name="delete" class="canDelete" /> DELETE <br/>
  <input type="hidden" name="experiment_id" class="experiment_id" value="{{experiment_id}}">
</p>

tardis/tardis_portal/templates/tardis_portal/ajax/add_group_result.html
<div class="access_list_group">
  <p>
    <strong>{{ group.name }}</strong>
    <a class="change_group" href="{{experiment_id}}/access_list/change/group/{{group.id}}"><img src="/site_media/images/icon_changelink.gif"></a>
    <a class="remove_group" href="{{experiment_id}}/access_list/remove/group/{{group.id}}"><img src="/site_media/images/icon_deletelink.gif"></a>
    <br/>
    <br/>
  </p>
</div> <!-- access_list_group -->

tardis/tardis_portal/templates/tardis_portal/ajax/add_user_result.html
<div class="access_list_user">
  <p>
    <strong>{{ user.username }}</strong> ({{user.email}})
    <a class="change_user" href="{{experiment_id}}/access_list/change/user/{{user.username}}"><img src="/site_media/images/icon_changelink.gif"></a>
    <a class="remove_user" href="{{experiment_id}}/access_list/remove/user/{{user.username}}"><img src="/site_media/images/icon_deletelink.gif"></a>
    <br/>
    <br/>
  </p>
</div> <!-- access_list_user -->

tardis/tardis_portal/templates/tardis_portal/ajax/add_user_to_group_result.html
<div class="access_list_user">
  <p>
    {% if user.groupadmin_set.count %}
      <img src="/site_media/images/icon_adminstrator.jpg">
    {% else %}
      <img src="/site_media/images/icon_user.jpg">
    {% endif %}
    <strong>{{ user.username }}</strong> ({{user.email}})
    <a class="remove_user" href="/group/{{group_id}}/remove/{{user.username}}/"><img src="/site_media/images/icon_deletelink.gif"></a>
    </div>
    <br/>
  </p>
</div> <!-- access_list_user -->

tardis/tardis_portal/templates/tardis_portal/ajax/experiment_description.html
{% load parametertypecheck %}
{% block script %}
<script type="text/javascript">
$(document).ready(function() {
    $(".dataset_metadata_toggle").toggle(
	function(){
	    $(this).text("[Show]");
	    var href= $(this).attr("href");
	    $(href).hide();
	},
	function(){
	    $(this).text("[Hide]");
	    var href= $(this).attr("href");
	    $(href).show();
	}
    );
    $(".dataset_metadata_toggle").click();
});

</script>
{% endblock %}

<div id="experiment_description">

  <p>
    <strong>Authors: </strong><br/>
    {% for author in authors %}
      {{ author.author }}{% if not forloop.last %},{% endif %}
    {% endfor %}
  </p>

  <p>
    <strong>Abstract: </strong>
    <div class="abstract">
      {{ experiment.description|safe }}
    </div>
  </p>

  {% if experiment.handle %}
    <p>
      <strong>Persistent Handle:</strong>
      <a href="{{ handle }}/{{ experiment.handle }}">{{ experiment.handle }}</a><br/>
    </p>
  {% endif %}

  <p>
    <strong>Institution:</strong>
    {{experiment.institution_name}}<br/>
  </p>

  {% if experiment.start_time and experiment.end_time %}
    <p>
      <strong>Date:</strong>
      {{ experiment.start_time|date:"jS F Y H:i" }} - {{ experiment.end_time|date:"jS F Y H:i" }}<br/>
    </p>
  {% endif %}

  <p>
    {% if experiment.experimentparameterset_set.count %}
      <div class="dataset_extrainfo">
	<strong>Experiment Metadata: </strong><a class="dataset_metadata_toggle" href="#dataset_metadata_{{forloop.counter}}">[Show]</a>
	<div class="dataset_metadata" id="dataset_metadata_{{forloop.counter}}">
	  <ul>
	    {% for parameterset in experiment.experimentparameterset_set.all %}
              <p><strong><em>Schema: {{parameterset.schema}}</em></strong></p>

	      {% for parameter in parameterset.experimentparameter_set.all %}
                <li><strong>{{ parameter.name.full_name }}: </strong>
		{% if parameter.name.is_numeric %}
                  {{ parameter.numerical_value }} {{ parameter.name.units }}
                {% else %}
                  {{ parameter.string_value|eparametertypecheck:parameter.id|safe }}
                {% endif %}
		</li>
              {% endfor %}
	      <br/><br/>
            {% endfor %}
	  </ul>
	</div>
      </div>
    {% endif %}
  </p>

  <p>
    <strong>Dataset Information:</strong>
    <div>
      <!-- <strong>Dataset Metadata: </strong>	 -->
      <div class="dataset_information">
	<ul>
	  <li><strong>Datasets:</strong> {{experiment.dataset_set.all.count}}</li>
	  <li><strong>Files:</strong> {{datafiles.count}}</li>
	  <li><strong>Size:</strong> {{size|filesizeformat}}</li>
	</ul>
      </div>
    </div>
  </p>

  <p>
    <strong>Experiment Last Updated:</strong>
    {{ experiment.update_time|date:"jS F Y H:i" }}<br/>
  </p>
  <div class="download_entire_experiment">
    {% for p in protocols %}
      <p>
	{% if p %}
	  <strong><a href="/{{p}}/download/experiment/{{experiment.id}}/">Download Entire Experiment ({{p|upper}})</a></strong><br/>
	{% else %}
	  <strong><a href="/download/experiment/{{experiment.id}}/">Download Entire Experiment</a></strong><br/>
	{% endif %}
      </p>
    {% endfor %}
  </div>

  <p align="right">
    <br/>
    {% if owners %}
      <strong>Experiment Administrators </strong><br/>
      {% for owner in owners %}
        {{ owner.username }} {% if owner.email %}(<a href="mailto:{{owner.email}}">{{ owner.email}}</a>{% endif %}){% if not forloop.last %}<br/>{% endif %}
      {% endfor %}
  </p>
{% endif %}

</div>

tardis/tardis_portal/templates/tardis_portal/ajax/group_list.html
{% for group in groups %}{{ group.name }} ~ {% endfor %}

tardis/tardis_portal/templates/tardis_portal/ajax/remove_member_result.html
OK

tardis/tardis_portal/templates/tardis_portal/ajax/remove_user_result.html
OK

tardis/tardis_portal/templates/tardis_portal/ajax/upload_files.html
{% load uploadify_tags %}
<div class="upload_files_box">
<b>{{ message }}</b>
<br/><br/>
{% multi_file_upload upload_complete_url dataset_id %}
<br/>
<strong><a id="upload_go" href="javascript:$('#fileInput').uploadifyUpload();">Upload Now</a></strong>
<br/>
</div>
<br/>

tardis/tardis_portal/templates/tardis_portal/ajax/user_list.html
{% for user in users %}{{ user.username }} {% endfor %}