tardis/apps/mrtardis/urls.py
from django.conf.urls.defaults import patterns

urlpatterns = patterns('tardis.apps.mrtardis.views',
                       (r'^index/(?P<experiment_id>\d+)/$',
                        'index'),
                       (r'^test_user_setup/(?P<experiment_id>\d+)/$',
                        'test_user_setup'),
                       (r'^MRform/(?P<experiment_id>\d+)/$',
                        'MRform'),
                       (r'^parForm/(?P<experiment_id>\d+)/$',
                        'parForm'),
                       (r'^displayResults/(?P<experiment_id>\d+)/$',
                        'displayResults'),
                       (r'^type_filtered_file_list/(?P<dataset_id>\d+)/$',
                        'type_filtered_file_list'),
                       (r'^extractPDBzips/(?P<dataset_id>\d+)/$',
                        'extractPDBzips'),
                       )

tardis/urls.py
from django.contrib import admin
admin.autodiscover()
from django.contrib.auth.views import logout
from django.conf.urls.defaults import patterns, include
from django.views.generic import list_detail
from django.conf import settings
from registration.views import register

from tardis.tardis_portal.models import Equipment
from tardis.tardis_portal.views import getNewSearchDatafileSelectionForm
from tardis.tardis_portal.forms import RegistrationForm

core_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^$', 'index'),
    (r'^site-settings.xml/$', 'site_settings'),
    (r'^about/$', 'about'),
    (r'^partners/$', 'partners'),
    (r'^stats/$', 'stats'),
    (r'^import_params/$', 'import_params'),
)

experiment_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^view/(?P<experiment_id>\d+)/$', 'view_experiment'),
    (r'^edit/(?P<experiment_id>\d+)/$', 'edit_experiment'),
    (r'^view/$', 'experiment_index'),
    (r'^register/$', 'register_experiment_ws_xmldata'),
    (r'^register/internal/$', 'register_experiment_ws_xmldata_internal'),
    (r'^view/(?P<experiment_id>\d+)/publish/$', 'publish_experiment'),
    (r'^create/$', 'create_experiment'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/add/user/'
     '(?P<username>[\w\.]+)$', 'add_experiment_access_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/remove/user/'
     '(?P<username>[\w\.]+)/$', 'remove_experiment_access_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/change/user/'
     '(?P<username>[\w\.]+)/$', 'change_user_permissions'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/user/$',
     'retrieve_access_list_user'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/add/group/'
     '(?P<groupname>[\w\s\.]+)$', 'add_experiment_access_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/remove/group/'
     '(?P<group_id>\d+)/$', 'remove_experiment_access_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/change/group/'
     '(?P<group_id>\d+)/$', 'change_group_permissions'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/group/$',
     'retrieve_access_list_group'),
    (r'^control_panel/(?P<experiment_id>\d+)/access_list/external/$',
     'retrieve_access_list_external'),
    (r'^control_panel/$', 'control_panel'),

    )

accounts_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^login/$', 'login'),
    (r'^manage_auth_methods/$', 'manage_auth_methods'),
    (r'^register/$', register,
     {'form_class': RegistrationForm}),
    (r'', include('registration.urls')),
    )

ajax_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^parameters/(?P<dataset_file_id>\d+)/$', 'retrieve_parameters'),
    (r'^xml_data/(?P<dataset_file_id>\d+)/$', 'retrieve_xml_data'),
    (r'^datafile_list/(?P<dataset_id>\d+)/$', 'retrieve_datafile_list'),
    (r'^user_list/$', 'retrieve_user_list'),
    (r'^group_list/$', 'retrieve_group_list'),
    (r'^upload_complete/$', 'upload_complete'),
    (r'^upload_files/(?P<dataset_id>\d+)/$', 'upload_files'),
    (r'^experiment_description/(?P<experiment_id>\d+)/$',
     'experiment_description'),
    (r'^experiment_datasets/(?P<experiment_id>\d+)/$', 'experiment_datasets'),
    )

download_urls = patterns(
    'tardis.tardis_portal.download',
    (r'^datafile/(?P<datafile_id>\d+)/$', 'download_datafile'),
    #(r'^dataset/(?P<dataset_id>\d+)/$', 'download_dataset'),
    (r'^experiment/(?P<experiment_id>\d+)/$', 'download_experiment'),
    (r'^datafiles/$', 'download_datafiles'),
    )

search_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^equipment/$', 'search_equipment'),
    (r'^experiment/$', 'search_experiment'),
    (r'^datafile/$', 'search_datafile'),
    )

group_urls = patterns(
    'tardis.tardis_portal.views',
    (r'^(?P<group_id>\d+)/$', 'retrieve_group_userlist'),
    (r'^(?P<group_id>\d+)/add/(?P<username>[\w\.]+)$',
     'add_user_to_group'),
    (r'^(?P<group_id>\d+)/remove/(?P<username>[\w\.]+)/$',
     'remove_user_from_group'),
    )

apppatterns = patterns('',)
for app in settings.TARDIS_APPS:
    apppatterns += patterns('tardis.apps',
                            (r'^%s/' % app,
                             include('%s.%s.urls' %
                                     (settings.TARDIS_APP_ROOT, app))))

urlpatterns = patterns(
    # (r'^search/quick/$', 'tardis.tardis_portal.views.search_quick'),
    '',
    (r'', include(core_urls)),

    # Experiment Views
    (r'^experiment/', include(experiment_urls)),

    # Download Views
    (r'^download/', include(download_urls)),

    # Ajax Views
    (r'^ajax/', include(ajax_urls)),

    # Seach Views
    (r'^search/', include(search_urls)),

    # Account Views
    (r'^accounts/', include(accounts_urls)),

    # Group Views
    (r'^groups/$', 'tardis.tardis_portal.views.manage_groups'),
    (r'^group/', include(group_urls)),

    # Equipment Views
    (r'^equipment/$', list_detail.object_list,
     {'queryset': Equipment.objects.all(),
      'paginate_by': 15,
      'extra_context':
      {'searchDatafileSelectionForm': getNewSearchDatafileSelectionForm()}}),
    (r'^equipment/(?P<object_id>\d+)/$', list_detail.object_detail,
     {'queryset': Equipment.objects.all()}),

    # Display Views
    (r'^displayExperimentImage/(?P<experiment_id>\d+)/'
     '(?P<parameterset_id>\d+)/(?P<parameter_name>\w+)/$',
     'tardis.tardis_portal.views.display_experiment_image'),
    (r'^displayDatasetImage/(?P<dataset_id>\d+)/(?P<parameterset_id>\d+)/'
     '(?P<parameter_name>\w+)/$',
     'tardis.tardis_portal.views.display_dataset_image'),
    (r'^displayDatafileImage/(?P<dataset_file_id>\d+)/'
     '(?P<parameterset_id>\d+)/(?P<parameter_name>\w+)/$',
    'tardis.tardis_portal.views.display_datafile_image'),

    # Login/out
    (r'^login/$', 'tardis.tardis_portal.views.login'),
    (r'^logout/$', logout, {'next_page': '/'}),

    # Media
    (r'site_media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.STATIC_DOC_ROOT}),
    (r'media/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.ADMIN_MEDIA_STATIC_DOC_ROOT}),

    # Admin
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),

    (r'^upload/(?P<dataset_id>\d+)/$', 'tardis.tardis_portal.views.upload'),

    # Apps
    (r'^apps/', include(apppatterns)),
)

tardis/apps/mrtardis/models.py
from django.db import models
from django.contrib.auth.models import User


class HPCUser(models.Model):
    """
    holds hpc log in information for a user account.
    """
    user = models.ForeignKey(User, unique=True)
    hpc_username = models.CharField(max_length=20)
    testedConnection = models.BooleanField()

    def __unicode__(self):
        return self.user.username

tardis/apps/mrtardis/forms.py
from django import forms
#from django.forms.formsets import formset_factory
import tardis.apps.mrtardis.utils as utils
from tardis.tardis_portal.logger import logger


class HPCSetupForm(forms.Form):
    hpc_username = forms.CharField(max_length=20)


# examples in comments
class MRForm(forms.Form):
    # "FP" single value or array. needs selector
    f_value = forms.ChoiceField(label="F column")
    # "SIGFP" same functionality as f_value
    sigf_value = forms.ChoiceField(label="SIGF column")
    mol_weight = forms.FloatField(
                                 label="Molecular weight")  # "11807"
    # alternative to MW, calculate MW from sequence
    sequence = forms.CharField(max_length=2000, required=False,
                               label="Protein sequence, if MW is not known",
                               widget=forms.Textarea(attrs={'cols': 40,
                                                            'rows': 4}))
    # "SEKIIHLTDDSFDTDVLKADGAILVDFWAEWCGPCKMIAPILDEIADEYQGKLTVAKLNIDQNPGTAPKYG
    #  IRGIPTLLLFKNGEVAATKVGALSKGQLKEFLDANLA"
    num_in_asym = forms.IntegerField(
                                  label="Number of Molecules in ASU")  # "2"
    space_group = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        label="Space Groups you wish to use")
    # ["P6","P61"]
    sg_all = forms.BooleanField(label="SG-alternative All", required=False,
                                help_text="Let Phaser determine point " +
                                "group and try all space groups of that " +
                                "point group in addition to space groups " +
                                "selected above",
                                initial=False)
    packing = forms.IntegerField(initial=10, label="Packing")  # "10"
    ensemble_number = forms.IntegerField(
        label="Number of copies to search for")
    # rmsd = forms.CharField(max_length=20)  # "1.0"

    def __init__(self, f_choices, sigf_choices, sg_num, *args, **kwargs):
        super(MRForm, self).__init__(*args, **kwargs)
        self.fields['f_value'].choices = f_choices
        self.fields['sigf_value'].choices = sigf_choices
        sgroups = utils.getGroupNumbersFromNumber(sg_num)
        sg_choices = []
        for sg in sgroups:
            sg_choices.append((sg, utils.sgNumNameTrans(number=sg)))
        self.fields['space_group'].choices = sg_choices
        self.fields['space_group'].initial = \
            (sg_num, utils.sgNumNameTrans(number=sg_num))

    def clean(self):
        logger.debug("starting to clean MRparam form")
        cleaned_data = self.cleaned_data
        mol_weight = cleaned_data.get("mol_weight")

        if not mol_weight:
            sequence = cleaned_data.get("sequence")
            if sequence:
                mol_weight = utils.calcMW(sequence)
                cleaned_data["mol_weight"] = mol_weight
            else:
                raise forms.ValidationError("Please enter either a " +
                    "number for the molecular weight or an amino acid " +
                                            "sequence for your input data.")
        logger.debug(repr(self._errors))
        logger.debug("ending to clean MRparam form")
        return cleaned_data


class RmsdForm(forms.Form):
    rmsd = forms.FloatField(min_value=0.8, max_value=2.6)

#RmsdFormset = formset_factory(RmsdForm)
#formset = RmsdFormset()
#for form in formset.forms:


class selectDSForm(forms.Form):
    dataset = forms.ChoiceField()

    def __init__(self, choices):
        super(selectDSForm, self).__init__()
        self.fields['dataset'].choices = choices


class DatasetDescriptionForm(forms.Form):
    description = forms.CharField(widget=forms.TextInput(attrs={'size': '40'}))

tardis/apps/mrtardis/templates/mrtardis/MRform.html
<script type="text/javascript">
$(document).ready(function(){
    function updateParForm() {
	$.ajax({
	    type: "POST",
	    url: "{% url tardis.apps.mrtardis.views.parForm experiment_id %}",
	    data: {
		dataset: {{ dataset }}
	    },
	    success: function(data) {
		$("#parForm").html(data);
	    }
	});
    }
    function updateFileList(type) {
	$.ajax({
	    type: "POST",
	    url: "{% url tardis.apps.mrtardis.views.type_filtered_file_list dataset.id %}",
	    data: {
		type: type,
	    },
	    success: function(data) {
		console.log(data);
		console.log(type);
		$(type).html(data);
	    }
	});
    }

    function extractPDBzips() {
	console.log("nothing");
	$.ajax({
	    type: "GET",
	    url: "{% url tardis.apps.mrtardis.views.extractPDBzips dataset.id %}",
	    success: function(data) {
		updateFileList(".pdb");
	    }
	});
    }
    updateFileList(".mtz");
    updateFileList(".pdb");

    $('.upload_files_link').bind('click', function( event ){
	$('.upload_files_container').each(function(index) {
            $(this).html("");
	});
	$('.upload_files_link').each(function(index) {
            $(this).show();
	});
	var message = escape( $(this).html());
	$(this).hide();
	$(this).siblings(".upload_files_container"
			).load("/ajax/upload_files/" + {{dataset.id}} + "/" + "?message=" +  message );
	$("#uploadify").die("allUploadsComplete");
	if (message.indexOf("MTZ") != -1) {
	    $("#uploadify").live("allUploadsComplete",
				 function(e, data){
				     updateFileList(".mtz");
				     updateParForm();
				 });
	} else if (message.indexOf("PDB") != -1) {
	    console.log("pdb if statement");
	    $("#uploadify").live("allUploadsComplete",
				 function(e, data){
				     console.log("we're bound");
				     extractPDBzips();
				 });
	}
    });
});
</script>
<h2>Job/dataset name: {{ dataset.description }}</h2>
<h3>MTZ file</h3>
<p><b>Already stored files</b>
<div id="fileList" class="mtz">
</div></p>
<p><b>Please upload your structure factors as MTZ file.</b> <br/>If you accidentally upload the wrong one, please cancel this form (see below) and start over.
</p>
<div class="uploadMTZfile">
  <a class="upload_files_link">Upload your MTZ file</a>
  <div class="upload_files_container"></div>
</div>

<h3>PDB file(s)</h3>
<p><b>Already stored files</b>
<div id="fileList" class="pdb">
</div></p>
<p><b>Please upload one or more PDB files.</b><br/> You can upload them separately or in a zip file or mix both.
</p>
<div class="uploadPDBfiles">
  <a class="upload_files_link">Upload your PDB file(s)</a>
  <div class="upload_files_container"></div>
  <input class="dataset_id" type="hidden" value="{{dataset.id}}" />
</div>

<h3>Run parameters</h3>
<p>These files are going to be used for the molecular replacements
<div id="fileList" class="mtz"></div>
<div id="fileList" class="pdb"></div>
<div id="parForm">
</div>
</p>


<!-- debug <p>
Dataset ID: {{ dataset }}
Experiment ID: {{ experiment_id }}
</p> -->

tardis/apps/mrtardis/templates/mrtardis/displayResults.html
<h3>Results of  {{ sometext }}</h3>
<p>
Experiment ID: {{ experiment_id }}
</p>

tardis/apps/mrtardis/templates/mrtardis/file_list.html
<ul>
{% for datafile in filequeryset %}
  <li class="datafile">
    {{ datafile.filename }}
  </li>
{% endfor %}
</ul>

tardis/apps/mrtardis/templates/mrtardis/index.html
<script type="text/javascript">
$(document).ready(function() {

    // testing user's HPC readiness and showing setup help if they are not set up
    var username = "{{ hpc_username }}";
    if (username == "False") {
	$("#HPCset-up").hide();
	$.ajax({
	    url: "{% url tardis.apps.mrtardis.views.test_user_setup experiment_id %}",
	    success:
 	    function(data){
		$("#setupHPC").html(data);
		$("#setupHPC").show();
		//$("#mrtardis").hide();
	    },
	       dataType: "html",
	      });
    } else {
	$("#mrtardis").show();
	$("#HPCset-up").show();
	$("#setupHPC").hide();
    }

    // responding to the different requests/forms

    function respondToForm(postdata) {
	$.ajax({
	    type: "POST",
	    url: "{% url tardis.apps.mrtardis.views.MRform experiment_id %}",
	    data: postdata,
	    success: function(data) {
		$("#mrtardis").html(data);
	    }
	});
    }
    $("form[id=newDS]").bind("submit", function() {
	postdata = {'action': 'newDS',
		    'description': $("#id_description").val(),
		   }
	respondToForm(postdata);
	return false;
    });
    $("form[id=continueDS]").bind("submit", function() {
	postdata = {'action': 'continue',
		    'dataset': $("#continueDS #id_dataset").val(),
		   }
	respondToForm(postdata);
	return false;
    });
    $("form[id=rerunDS]").bind("submit", function() {
	postdata = {'action': 'rerunDS',
		    'dataset': $("#rerunDS #id_dataset").val(),
		   }
	respondToForm(postdata);
	return false;
    });

    // different url for displaying data
    $("form[id=viewDS]").bind("submit", function() {
	postdata = {'action': 'viewDS',
		    'dataset': $("#viewDS #id_dataset").val(),
		   }
	$.ajax({
	    type: "POST",
	    url: "{% url tardis.apps.mrtardis.views.displayResults experiment_id %}",
	    data: postdata,
	    //dataType: "json",
	    success: function(data) {
		$("#mrtardis").html(data);
	    }
	});
	return false;
    });


});
</script>
<p id="setupHPC"></p>
  <h2>Simple Molecular Replacements on the Monash Grid</h2>
<div id="mrtardis">
  <h3>Please select what you would like to do next:</h3>
  <p>
    <b>Set up a new run</b>
    <form id="newDS">{{ newDSForm }}
    <input type="submit" value="Create" />
    </form>
  </p>
  {% if continueForm %}
    <p>
      <b>Continue an interrupted setup</b>
      <form id="continueDS">{{ continueForm }}
      <input type="submit" value="Continue" />
      </form>
    </p>
  {% endif %}
  {% if viewForm %}
    <p>
      <b>View the results of finished runs</b>
      <form >{{ viewForm }}</form>
    </p>
  {% endif %}
  {% if rerunForm %}
    <p>
      <b>Copy, edit and re-run a previous Molecular Replacement</b>
      <form >{{ rerunForm }}</form>
    </p>
  {% endif %}

<!-- debug only
  <p style="text-align:right;font-size:80%;">
    Experiment id: {{ experiment_id }}
  </p> -->
</div>
<p id="HPCset-up" style="text-align: right; font-size:80%;">
Your HPC resource is set up and ready to use. You are using authcate username {{ hpc_username }} on the Monash Sun Grid.<br /><a href="changeUsername" >Change username</a>
</p>

tardis/apps/mrtardis/templates/mrtardis/usersetup.html
<script type="text/javascript">
console.log("logging works");
$(document).ready(function(){
    $("form[id=HPCSetupForm]").live("submit", function() {
	console.log("submitting form");
	$.post("{% url tardis.apps.mrtardis.views.test_user_setup experiment_id %}",
	       $("form[id=HPCSetupForm]").serialize(),
	       function(data) {
		   $("#mrtardis").html(data);
	       });
	return false;
    });
});
</script>
<b>Please first set up your HPC connection in two steps:</b>
<ol>
<li>Please copy the following public key and paste it into the <i>.ssh/authorized_keys</i> file in your Monash Sun Grid home directory.
<textarea cols="100" rows="5" readonly>
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA10u+WBDCBpu2z/Sk4xCx7ARCB6kLSCrfFnNoF3/Rq9365k8PmOmx7dANKpBnqdihlxLeqJqlM3s8snvWtad0e0rA50jX5tCXd8ToNtHJmCYVWDndjqKB7qfjZNPnSB4x2XGcnw5XS6336J7/YHWly9evebwAJPHyVCHwF9TCwvwc7Lx46PFf1x4n3sX5bRUkPDNZMWETEExWeIelGZiBMNpum86FUmsl2OrdHsSLoJ9Xczo1Y1pYDZQPOKRcGriqgKfeyQDp37uBg1XcLbeLrwyVrqIvXMXMzVGHSDSthI2Tvy2y/EJ9Pg01fkd2iPAjjhV3gLiVRxYHbhcdJdWvkQ== grischa@dvr-merc-002.adm.monash.edu.au
</textarea>
</li>
<li>Enter your Monash Authcate here and press submit<br/>
<form id="HPCSetupForm" method="POST">
{{ HPCSetupForm }} <input id="HPCSetupForm" type="submit" value="Submit" />
</form>
</li>
</ol>